Added version check for CursorAnchorInfo, which caused a java.lang.NoClassDefFoundError on pre-lollipop versions, since the class was included in sdk 21